services:
  payment-postgres:
    image: postgres:17
    container_name: kazakhexpress-payment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kazakhexpress
    ports:
      - "5432:5432"
    volumes:
      - payment-postgres-data:/var/lib/postgresql/data
      - ../payment-service/migrations/001_create_payments.sql:/docker-entrypoint-initdb.d/001_create_payments.sql:ro
      - ../payment-service/migrations/002_extend_payments.sql:/docker-entrypoint-initdb.d/002_extend_payments.sql:ro

  payment-redis:
    image: redis:7
    container_name: kazakhexpress-payment-redis
    ports:
      - "6379:6379"

  payment-rabbitmq:
    image: rabbitmq:3-management
    container_name: kazakhexpress-payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: kazakhexpress-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  payment-postgres-data:
  grafana-data:
