apiVersion: 1

datasources:
  - name: Payment PostgreSQL 17
    uid: payment-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: kazakhexpress
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
